language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install --upgrade pip
  - pip install --upgrade setuptools wheel
  - pip install --upgrade pytest pytest-cov codecov
  - pip install --upgrade .

script: py.test --cov=fftoptionlib tests/

after_success:
  codecov
